title:   Anushka Jayalath
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br><br>
  I'm a skilled data analyst who's all about finding those nuggets of wisdom that help businesses make savvy decisions. I enjoy creating interactive dashboards and playing with complex SQL queries to make data come to life. With my tech skills in SQL, Python, and Power BI, I turn customer behaviors into easy-to-understand visuals.
  <br><br>
  I'm a self-starter and love learning new things on my own. I've taken the lead on projects that made a real impact on business revenue and the user experience. I'm all about teamwork too—working closely with different teams has helped me build strong relationships and make sure our solutions align with what the business wants.
  <br><br>
  <a href="https://www.linkedin.com/in/anushka-jayalath/">View My LinkedIn Profile</a>
  <br><br><br>
  <a href="https://www.notion.so/anushkajayalath/Portfolio-Anushka-Jayalath-5d7604e5a5f6401b867c994614505e39">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal   
 
